    version: '3'
    services:
      bitwarden:
        image: vaultwarden/server
        container_name: vaultwarden
        restart: always
        volumes:
          - ./bw-data:/data
        ports:
          - "80:80"
          - "443:443"
        environment:
          WEBSOCKET_ENABLED: "true" # Enable WebSocket notifications
          SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED}  # Disable signups (set to "true" to allow)
